export interface DirectiveExample {
  id: string;
  name: string;
  ts: string;
  html: string;
  css?: string;
}

const L = (lines: string[]) => lines.join('\n');

export const DIRECTIVE_EXAMPLES: DirectiveExample[] = [
  {
    id: 'reveal',
    name: 'reveal',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { Reveal } from '@angular-gsap/core';`,
      ``,
      `@Component({`,
      `  selector: 'app-hero',`,
      `  imports: [Reveal],`,
      `  templateUrl: './hero.component.html',`,
      `})`,
      `export class HeroComponent {}`,
    ]),
    html: L([
      `<h1 reveal>Fades up when the page renders</h1>`,
      ``,
      `<section reveal="fade-right" [delay]="0.2" [distance]="40">`,
      `  A little later, from the left.`,
      `</section>`,
      ``,
      `<p reveal="fade-up" on="scroll">`,
      `  And this one waits until you scroll to it.`,
      `</p>`,
    ]),
  },
  {
    id: 'stagger',
    name: 'stagger',
    ts: L([
      `import { Component, signal } from '@angular/core';`,
      `import { Stagger } from '@angular-gsap/core';`,
      ``,
      `@Component({`,
      `  selector: 'app-features',`,
      `  imports: [Stagger],`,
      `  templateUrl: './features.component.html',`,
      `})`,
      `export class FeaturesComponent {`,
      `  features = signal(['Fast', 'Small', 'Typed']);`,
      `}`,
    ]),
    html: L([
      `<ul stagger="0.08" preset="scale-in">`,
      `  @for (feature of features(); track feature) {`,
      `    <li>{{ feature }}</li>`,
      `  }`,
      `</ul>`,
    ]),
  },
  {
    id: 'splitReveal',
    name: 'splitReveal',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { SplitReveal } from '@angular-gsap/core';`,
      ``,
      `// needs provideGsap({ plugins: [SplitText] })`,
      `@Component({`,
      `  selector: 'app-quote',`,
      `  imports: [SplitReveal],`,
      `  templateUrl: './quote.component.html',`,
      `})`,
      `export class QuoteComponent {}`,
    ]),
    html: L([
      `<blockquote splitReveal="lines" [distance]="30">`,
      `  Great interfaces move with intent,`,
      `  and text is no exception.`,
      `</blockquote>`,
      ``,
      `<h2 splitReveal="chars" on="scroll" [each]="0.02">`,
      `  Character by character`,
      `</h2>`,
    ]),
  },
  {
    id: 'scrambleText',
    name: 'scrambleText',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { ScrambleText } from '@angular-gsap/core';`,
      ``,
      `// needs provideGsap({ plugins: [ScrambleTextPlugin] })`,
      `@Component({`,
      `  selector: 'app-status',`,
      `  imports: [ScrambleText],`,
      `  templateUrl: './status.component.html',`,
      `})`,
      `export class StatusComponent {}`,
    ]),
    html: L([
      `<p scrambleText>decodes into this sentence</p>`,
      ``,
      `<h2 scrambleText="ONLINE" chars="01" on="scroll">`,
      `  offline`,
      `</h2>`,
    ]),
  },
  {
    id: 'counter',
    name: 'counter',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { Counter } from '@angular-gsap/core';`,
      ``,
      `@Component({`,
      `  selector: 'app-stats',`,
      `  imports: [Counter],`,
      `  templateUrl: './stats.component.html',`,
      `})`,
      `export class StatsComponent {}`,
    ]),
    html: L([
      `<div class="stats">`,
      `  <span [counter]="12500"></span>`,
      ``,
      `  <span [counter]="98.6" [decimals]="1"></span>`,
      ``,
      `  <span [counter]="404" on="scroll" [duration]="2"></span>`,
      `</div>`,
    ]),
  },
  {
    id: 'parallax',
    name: 'parallax',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { Parallax } from '@angular-gsap/core';`,
      ``,
      `// needs provideGsap({ plugins: [ScrollTrigger] })`,
      `@Component({`,
      `  selector: 'app-banner',`,
      `  imports: [Parallax],`,
      `  templateUrl: './banner.component.html',`,
      `  styleUrl: './banner.component.css',`,
      `})`,
      `export class BannerComponent {}`,
    ]),
    html: L([
      `<section class="banner">`,
      `  <img parallax="0.25" src="mountains.webp" alt="" />`,
      ``,
      `  <div class="card" parallax="-0.15">`,
      `    Moves against the scroll.`,
      `  </div>`,
      `</section>`,
    ]),
    css: L([
      `.banner {`,
      `  position: relative;`,
      `  overflow: hidden;`,
      `  min-height: 60vh;`,
      `}`,
    ]),
  },
  {
    id: 'drawSvg',
    name: 'drawSvg',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { DrawSvg } from '@angular-gsap/core';`,
      ``,
      `// needs provideGsap({ plugins: [DrawSVGPlugin] })`,
      `@Component({`,
      `  selector: 'app-mark',`,
      `  imports: [DrawSvg],`,
      `  templateUrl: './mark.component.html',`,
      `})`,
      `export class MarkComponent {}`,
    ]),
    html: L([
      `<!-- on the svg: every stroked child draws, staggered -->`,
      `<svg drawSvg on="scroll" [each]="0.2" viewBox="0 0 100 40">`,
      `  <path d="M 5 35 L 25 5 L 45 35" />`,
      `  <path d="M 55 35 L 75 5 L 95 35" />`,
      `</svg>`,
    ]),
  },
  {
    id: 'sequence',
    name: 'sequence',
    ts: L([
      `import { Component, signal } from '@angular/core';`,
      `import {`,
      `  Reveal,`,
      `  Sequence,`,
      `  SplitReveal,`,
      `  Stagger,`,
      `} from '@angular-gsap/core';`,
      ``,
      `@Component({`,
      `  selector: 'app-intro',`,
      `  imports: [Sequence, Reveal, Stagger, SplitReveal],`,
      `  templateUrl: './intro.component.html',`,
      `})`,
      `export class IntroComponent {`,
      `  tags = signal(['signals', 'zoneless', 'ssr']);`,
      `}`,
    ]),
    html: L([
      `<!-- children play in template order, 0.1s apart -->`,
      `<header sequence="0.1">`,
      `  <h1 reveal>First the title</h1>`,
      ``,
      `  <ul stagger preset="scale-in">`,
      `    @for (tag of tags(); track tag) {`,
      `      <li>{{ tag }}</li>`,
      `    }`,
      `  </ul>`,
      ``,
      `  <p splitReveal [at]="'<0.3'">`,
      `    Then this, overlapping the list.`,
      `  </p>`,
      `</header>`,
    ]),
  },
  {
    id: 'drag',
    name: 'drag',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { Drag } from '@angular-gsap/core';`,
      ``,
      `// needs provideGsap({ plugins: [Draggable, InertiaPlugin] })`,
      `@Component({`,
      `  selector: 'app-board',`,
      `  imports: [Drag],`,
      `  templateUrl: './board.component.html',`,
      `  styleUrl: './board.component.css',`,
      `})`,
      `export class BoardComponent {`,
      `  onDrop() {`,
      `    console.log('landed');`,
      `  }`,
      `}`,
    ]),
    html: L([
      `<div class="board">`,
      `  <div class="card" drag [snap]="80" (dragEnd)="onDrop()">`,
      `    Throw me`,
      `  </div>`,
      ``,
      `  <div class="card" drag="x" [inertia]="false">`,
      `    Horizontal only`,
      `  </div>`,
      `</div>`,
    ]),
    css: L([
      `.board {`,
      `  position: relative;`,
      `  height: 320px;`,
      `}`,
      ``,
      `.card {`,
      `  position: absolute;`,
      `  width: 120px;`,
      `}`,
    ]),
  },
  {
    id: 'scrollTo',
    name: 'scrollTo',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { ScrollTo } from '@angular-gsap/core';`,
      ``,
      `// smoother with provideGsap({ plugins: [ScrollToPlugin] });`,
      `// falls back to native scrollIntoView without it`,
      `@Component({`,
      `  selector: 'app-toc',`,
      `  imports: [ScrollTo],`,
      `  templateUrl: './toc.component.html',`,
      `})`,
      `export class TocComponent {}`,
    ]),
    html: L([
      `<nav>`,
      `  <button scrollTo="#pricing" [offsetY]="72">Pricing</button>`,
      `  <button scrollTo="#faq" [duration]="1.2">FAQ</button>`,
      `</nav>`,
      ``,
      `<section id="pricing">…</section>`,
      `<section id="faq">…</section>`,
    ]),
  },
  {
    id: 'observe',
    name: 'observe',
    ts: L([
      `import { Component, signal } from '@angular/core';`,
      `import { Observe } from '@angular-gsap/core';`,
      ``,
      `// needs provideGsap({ plugins: [Observer] })`,
      `@Component({`,
      `  selector: 'app-deck',`,
      `  imports: [Observe],`,
      `  templateUrl: './deck.component.html',`,
      `})`,
      `export class DeckComponent {`,
      `  slide = signal(0);`,
      ``,
      `  next() {`,
      `    this.slide.update((s) => Math.min(s + 1, 4));`,
      `  }`,
      ``,
      `  previous() {`,
      `    this.slide.update((s) => Math.max(s - 1, 0));`,
      `  }`,
      `}`,
    ]),
    html: L([
      `<!-- wheel, touch, and pointer, one stream -->`,
      `<section observe (up)="next()" (down)="previous()">`,
      `  Slide {{ slide() + 1 }} of 5`,
      `</section>`,
    ]),
  },
  {
    id: 'hover',
    name: 'hover',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { Hover } from '@angular-gsap/core';`,
      ``,
      `@Component({`,
      `  selector: 'app-menu',`,
      `  imports: [Hover],`,
      `  templateUrl: './menu.component.html',`,
      `})`,
      `export class MenuComponent {}`,
    ]),
    html: L([
      `<nav>`,
      `  <a hover routerLink="/docs">Docs</a>`,
      ``,
      `  <a hover="grow" routerLink="/examples">Examples</a>`,
      ``,
      `  <button hover="tilt" [amount]="6">Wiggle</button>`,
      `</nav>`,
    ]),
  },
];
