export interface DirectiveExample {
  id: string;
  name: string;
  ts: string;
  html: string;
  css?: string;
}

const L = (lines: string[]) => lines.join('\n');

export const DIRECTIVE_EXAMPLES: DirectiveExample[] = [
  {
    id: 'reveal',
    name: 'reveal',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { Reveal } from '@angular-gsap/core';`,
      ``,
      `@Component({`,
      `  selector: 'app-reveal',`,
      `  imports: [Reveal],`,
      `  templateUrl: './reveal.component.html',`,
      `  styleUrl: './reveal.component.css',`,
      `})`,
      `export class RevealComponent {}`,
    ]),
    html: L([
      `<div class="frame" #frame>`,
      `  <h1 reveal>Fades up when the page renders</h1>`,
      ``,
      `  <section reveal="fade-right" [delay]="0.2" [distance]="40">`,
      `    A little later, from the left.`,
      `  </section>`,
      ``,
      `  <!-- [scroller] is optional: drop it and the page scroll drives it -->`,
      `  <p reveal="fade-up" on="scroll" [scroller]="frame">`,
      `    And this one waits until you scroll the frame.`,
      `  </p>`,
      `</div>`,
    ]),
    css: L([
      `.frame {`,
      `  height: 15rem;`,
      `  overflow-y: auto;`,
      `}`,
    ]),
  },
  {
    id: 'stagger',
    name: 'stagger',
    ts: L([
      `import { Component, signal } from '@angular/core';`,
      `import { Stagger } from '@angular-gsap/core';`,
      ``,
      `@Component({`,
      `  selector: 'app-stagger',`,
      `  imports: [Stagger],`,
      `  templateUrl: './stagger.component.html',`,
      `})`,
      `export class StaggerComponent {`,
      `  features = signal(['Fast', 'Small', 'Typed']);`,
      `}`,
    ]),
    html: L([
      `<ul stagger="0.08" preset="scale-in">`,
      `  @for (feature of features(); track feature) {`,
      `    <li>{{ feature }}</li>`,
      `  }`,
      `</ul>`,
    ]),
  },
  {
    id: 'splitReveal',
    name: 'splitReveal',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { SplitReveal } from '@angular-gsap/core';`,
      ``,
      `// needs provideGsap({ plugins: [SplitText] })`,
      `@Component({`,
      `  selector: 'app-split-reveal',`,
      `  imports: [SplitReveal],`,
      `  templateUrl: './split-reveal.component.html',`,
      `})`,
      `export class SplitRevealComponent {}`,
    ]),
    html: L([
      `<blockquote splitReveal="lines" [distance]="30">`,
      `  Great interfaces move with intent,`,
      `  and text is no exception.`,
      `</blockquote>`,
      ``,
      `<h2 splitReveal="chars" on="scroll" [each]="0.02">`,
      `  Character by character`,
      `</h2>`,
    ]),
  },
  {
    id: 'scrambleText',
    name: 'scrambleText',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { ScrambleText } from '@angular-gsap/core';`,
      ``,
      `// needs provideGsap({ plugins: [ScrambleTextPlugin] })`,
      `@Component({`,
      `  selector: 'app-scramble-text',`,
      `  imports: [ScrambleText],`,
      `  templateUrl: './scramble-text.component.html',`,
      `})`,
      `export class ScrambleTextComponent {}`,
    ]),
    html: L([
      `<p scrambleText>decodes into this sentence</p>`,
      ``,
      `<h2 scrambleText="ONLINE" chars="01" on="scroll">`,
      `  offline`,
      `</h2>`,
    ]),
  },
  {
    id: 'counter',
    name: 'counter',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { Counter } from '@angular-gsap/core';`,
      ``,
      `@Component({`,
      `  selector: 'app-counter',`,
      `  imports: [Counter],`,
      `  templateUrl: './counter.component.html',`,
      `})`,
      `export class CounterComponent {}`,
    ]),
    html: L([
      `<div class="stats">`,
      `  <span [counter]="12500"></span>`,
      ``,
      `  <span [counter]="98.6" [decimals]="1"></span>`,
      ``,
      `  <span [counter]="404" on="scroll" [duration]="2"></span>`,
      `</div>`,
    ]),
  },
  {
    id: 'parallax',
    name: 'parallax',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { Parallax } from '@angular-gsap/core';`,
      ``,
      `// needs provideGsap({ plugins: [ScrollTrigger] })`,
      `@Component({`,
      `  selector: 'app-parallax',`,
      `  imports: [Parallax],`,
      `  templateUrl: './parallax.component.html',`,
      `  styleUrl: './parallax.component.css',`,
      `})`,
      `export class ParallaxComponent {}`,
    ]),
    html: L([
      `<!-- the blocks scrub against the frame, not the page -->`,
      `<div class="frame" #frame>`,
      `  <div class="runway">`,
      `    <span class="block" parallax="0.25" [scroller]="frame"></span>`,
      `    <span class="block" parallax="-0.15" [scroller]="frame"></span>`,
      `    <span class="block" parallax="0.15" [scroller]="frame"></span>`,
      `  </div>`,
      `</div>`,
    ]),
    css: L([
      `.frame {`,
      `  height: 15rem;`,
      `  overflow-y: auto;`,
      `}`,
      ``,
      `/* room to scroll while the blocks drift */`,
      `.runway {`,
      `  padding: 6rem 0 22rem;`,
      `}`,
    ]),
  },
  {
    id: 'drawSvg',
    name: 'drawSvg',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { DrawSvg } from '@angular-gsap/core';`,
      ``,
      `// needs provideGsap({ plugins: [DrawSVGPlugin] })`,
      `@Component({`,
      `  selector: 'app-draw-svg',`,
      `  imports: [DrawSvg],`,
      `  templateUrl: './draw-svg.component.html',`,
      `})`,
      `export class DrawSvgComponent {}`,
    ]),
    html: L([
      `<!-- on the svg: every stroked child draws, staggered -->`,
      `<svg drawSvg on="scroll" [each]="0.2" viewBox="0 0 100 40">`,
      `  <path d="M 5 35 L 25 5 L 45 35" />`,
      `  <path d="M 55 35 L 75 5 L 95 35" />`,
      `</svg>`,
    ]),
  },
  {
    id: 'sequence',
    name: 'sequence',
    ts: L([
      `import { Component, signal } from '@angular/core';`,
      `import {`,
      `  Reveal,`,
      `  Sequence,`,
      `  SplitReveal,`,
      `  Stagger,`,
      `} from '@angular-gsap/core';`,
      ``,
      `@Component({`,
      `  selector: 'app-sequence',`,
      `  imports: [Sequence, Reveal, Stagger, SplitReveal],`,
      `  templateUrl: './sequence.component.html',`,
      `})`,
      `export class SequenceComponent {`,
      `  tags = signal(['signals', 'zoneless', 'ssr']);`,
      `}`,
    ]),
    html: L([
      `<!-- children play in template order, 0.1s apart -->`,
      `<header sequence="0.1">`,
      `  <h1 reveal>First the title</h1>`,
      ``,
      `  <ul stagger preset="scale-in">`,
      `    @for (tag of tags(); track tag) {`,
      `      <li>{{ tag }}</li>`,
      `    }`,
      `  </ul>`,
      ``,
      `  <p splitReveal [at]="'<0.3'">`,
      `    Then this, overlapping the list.`,
      `  </p>`,
      `</header>`,
    ]),
  },
  {
    id: 'drag',
    name: 'drag',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { Drag } from '@angular-gsap/core';`,
      ``,
      `// needs provideGsap({ plugins: [Draggable, InertiaPlugin] })`,
      `@Component({`,
      `  selector: 'app-drag',`,
      `  imports: [Drag],`,
      `  templateUrl: './drag.component.html',`,
      `  styleUrl: './drag.component.css',`,
      `})`,
      `export class DragComponent {`,
      `  onDrop() {`,
      `    console.log('landed');`,
      `  }`,
      `}`,
    ]),
    html: L([
      `<div class="board">`,
      `  <div class="card" drag [snap]="80" (dragEnd)="onDrop()">`,
      `    Throw me`,
      `  </div>`,
      ``,
      `  <div class="card" drag="x" [inertia]="false">`,
      `    Horizontal only`,
      `  </div>`,
      `</div>`,
    ]),
    css: L([
      `.board {`,
      `  position: relative;`,
      `  height: 320px;`,
      `}`,
      ``,
      `.card {`,
      `  position: absolute;`,
      `  width: 120px;`,
      `}`,
    ]),
  },
  {
    id: 'scrollTo',
    name: 'scrollTo',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { ScrollTo } from '@angular-gsap/core';`,
      ``,
      `// smoother with provideGsap({ plugins: [ScrollToPlugin] });`,
      `// falls back to native scrollIntoView without it`,
      `@Component({`,
      `  selector: 'app-scroll-to',`,
      `  imports: [ScrollTo],`,
      `  templateUrl: './scroll-to.component.html',`,
      `})`,
      `export class ScrollToComponent {}`,
    ]),
    html: L([
      `<nav>`,
      `  <button scrollTo="#pricing" [offsetY]="72">Pricing</button>`,
      `  <button scrollTo="#faq" [duration]="1.2">FAQ</button>`,
      `</nav>`,
      ``,
      `<section id="pricing">…</section>`,
      `<section id="faq">…</section>`,
    ]),
  },
  {
    id: 'observe',
    name: 'observe',
    ts: L([
      `import { Component, signal } from '@angular/core';`,
      `import { Observe } from '@angular-gsap/core';`,
      ``,
      `// needs provideGsap({ plugins: [Observer] })`,
      `@Component({`,
      `  selector: 'app-observe',`,
      `  imports: [Observe],`,
      `  templateUrl: './observe.component.html',`,
      `})`,
      `export class ObserveComponent {`,
      `  slide = signal(0);`,
      ``,
      `  next() {`,
      `    this.slide.update((s) => Math.min(s + 1, 4));`,
      `  }`,
      ``,
      `  previous() {`,
      `    this.slide.update((s) => Math.max(s - 1, 0));`,
      `  }`,
      `}`,
    ]),
    html: L([
      `<!-- wheel, touch, and pointer, one stream -->`,
      `<section`,
      `  observe`,
      `  [preventDefault]="true"`,
      `  (up)="next()"`,
      `  (down)="previous()"`,
      `>`,
      `  Slide {{ slide() + 1 }} of 5`,
      `</section>`,
    ]),
  },
  {
    id: 'hover',
    name: 'hover',
    ts: L([
      `import { Component } from '@angular/core';`,
      `import { Hover } from '@angular-gsap/core';`,
      ``,
      `@Component({`,
      `  selector: 'app-hover',`,
      `  imports: [Hover],`,
      `  templateUrl: './hover.component.html',`,
      `})`,
      `export class HoverComponent {}`,
    ]),
    html: L([
      `<nav>`,
      `  <a hover routerLink="/docs">Docs</a>`,
      ``,
      `  <a hover="grow" routerLink="/examples">Examples</a>`,
      ``,
      `  <button hover="tilt" [amount]="6">Wiggle</button>`,
      `</nav>`,
    ]),
  },
];
